#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.1"
      when: "{{ ansible_version['full'] | version_compare('2.1', '<') }}"
      tags:
        - always
        - ansible-version

- hosts: wiki
  become: yes

  tasks:
    - name: checking wiki
      script: scripts/check_wiki.sh "{{ users }}"
      register: wiki_result

    - debug: msg="{{ wiki_result.stdout }}"

    - local_action: copy content={{ wiki_result.stdout }} dest=/tmp/watch_results.txt
