#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.1"
      when: "{{ ansible_version['full'] | version_compare('2.1', '<') }}"
      tags:
        - always
        - ansible-version

- hosts: apache
  become: yes

  tasks:
    - name: checking apache
      script: scripts/check_apache.sh "{{ users }}"
      register: apache_result

    - debug: msg="{{ apache_result.stdout }}"

    - local_action: copy content={{ apache_result.stdout }} dest=/tmp/watch_part2_results.txt
