#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.1"
      when: ansible_version['full'] | version_compare('2.1', '<')
      tags:
        - always
        - ansible-version

- hosts: apache
  become: yes

  # Use the users value stored in part1.
  vars:
    - HOME: "{{ lookup('env','HOME') }}"
    - users: "{{ lookup('file',  HOME + '/watch_users.txt') }}"

  tasks:
    - name: checking apache
      script: scripts/check_apache.sh "{{ users }}"
      register: apache_result

    - debug: msg="{{ apache_result.stdout }}"

    - local_action: blockinfile \
        block="{{ apache_result.stdout }}" \
        path="{{ HOME + '/preliminary_watch_results.txt' }}" \
        create=yes \
        marker=""

- hosts: tr
  become: yes

  vars:
    - HOME: "{{ lookup('env','HOME') }}"
    - users: "{{ lookup('file',  HOME + '/watch_users.txt') }}"

  tasks:
    - name: checking tracker
      script: scripts/check_tracker.sh "{{ users }}"
      register: tracker_result

    - debug: msg="{{ tracker_result.stdout }}"

    - local_action: blockinfile \
        block="{{ tracker_result.stdout }}" \
        path="{{ HOME + '/preliminary_watch_results.txt' }}" \
        marker=""

    - local_action: shell echo "]" >> "{{ HOME + '/preliminary_watch_results.txt' }}"

    - local_action: shell  scripts/combine_results.py \
        "{{ HOME + '/preliminary_watch_results.txt' }}" \
        > "{{ HOME + '/watch_results.txt' }}"
      tags: last
