#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.1"
      when: ansible_version['full'] | version_compare('2.1', '<')
      tags:
        - always
        - ansible-version

- hosts: wiki
  become: yes

  vars:
    - HOME: "{{ lookup('env','HOME') }}"

  vars_prompt:
    - name: "users"
      prompt: "Enter one or more UWNetIds. Use space to separate"
      private: no

  tasks:
    - debug: msg="users={{ users }}, HOME={{ HOME }}"

    - name: checking wiki
      script: scripts/check_wiki.sh "{{ users }}"
      register: wiki_result

    - debug: msg="{{ wiki_result.stdout }}"

    - local_action: copy content={{ wiki_result.stdout }} dest="{{ HOME }}/watch_results.txt"

    # Save users so we don't have to enter it again in part2.
    - local_action: copy content="{{ users }}" dest="{{ HOME }}/watch_users.txt"
