#!/usr/bin/env python
"""
Generate report from the JSON file.
"""

import argparse
import json
import sys

def build_parser(parser):
    parser.add_argument('-i', '--json-input-file', type=argparse.FileType(),
                        default='../../watch_results.txt',
                        help='file containing the JSON data generated by ansible. Default [%(default)s]')


class Reporter(object):
    def __init__(self, args):
        self.file = args.json_input_file

    def display(self):
        j = json.load(self.file)
        for user in sorted(j.keys()):
            print user
            for pack in sorted(j[user].keys()):
                sub = j[user][pack]
                if type(sub) == type({}):
                    print "  %s" % (pack,)
                    for k in sorted(j[user][pack].keys()):
                        subsub = j[user][pack][k]
                        if type(subsub) == type([]):
                            print "    %s" % (k,)
                            for kk in sorted(subsub):
                                if type(kk) == type({}):
                                    for kkk in sorted(kk.keys()):
                                        print "      %s" % (kkk,)
                                else:
                                    print "      %s" % (kk,)
                        else:
                            print "    %s: %s" % (k, j[user][pack][k])
                elif type(sub) == type([]): 
                    print "  %s" % (pack,)
                    for ele in sub:
                        print "    %s" % (ele,)
                else:
                    print "  %s: %s" % (pack, sub)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    build_parser(parser)
    reporter = Reporter(parser.parse_args(sys.argv[1:]))
    reporter.display()


if __name__ == '__main__':
    main()
